# Pandas Exercises
## Author: Matheus Ribeiro Alencar


### 1. Import pandas and read in the banklist.csv file into a dataframe called banks. 

In [ ]:
import pandas as pd

In [ ]:
banks = pd.read_csv('banklist.csv')

** Show the head of the dataframe **

In [ ]:
banks.head()

Bank Name                City  ST  \
0                                Fayette County Bank          Saint Elmo  IL   
1  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee  WI   
2                                     First NBC Bank         New Orleans  LA   
3                                      Proficio Bank  Cottonwood Heights  UT   
4                      Seaway Bank and Trust Company             Chicago  IL   

    CERT                Acquiring Institution Closing Date Updated Date  
0   1802            United Fidelity Bank, fsb    26-May-17     1-Jun-17  
1  30003  First-Citizens Bank & Trust Company     5-May-17     1-Jun-17  
2  58302                         Whitney Bank    28-Apr-17    23-May-17  
3  35495                    Cache Valley Bank     3-Mar-17    18-May-17  
4  19328                  State Bank of Texas    27-Jan-17    18-May-17

### 2. What are the column names? 

In [ ]:
# CODE HERE
banks.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

### 3. How many States (ST) are represented in this data set? 

In [ ]:
# CODE HERE
banks['ST'].nunique()

44

44

### 4. Get a list or array of all the states in the data set. 

In [ ]:
# CODE HERE

arr=banks['ST'].unique()
arr

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'],
      dtype=object)

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'], dtype=object)

### 5. What are the top 5 states with the most failed banks? 

In [ ]:
# CODE HERE
banks['ST'].value_counts().head()

GA    93
FL    75
IL    67
CA    41
MN    23
Name: ST, dtype: int64

ST
GA    93
FL    75
IL    67
CA    41
MN    23
Name: Bank Name, dtype: int64

### 6. What are the top 5 acquiring institutions? 

In [ ]:
# CODE HERE
banks['Acquiring Institution'].value_counts().head()

No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: Acquiring Institution, dtype: int64

No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: Acquiring Institution, dtype: int64

### 7. How many banks has the State Bank of Texas acquired? How many of them were actually in Texas?

In [ ]:
# CODE HERE
answer7 = banks[banks['Acquiring Institution'] == 'State Bank of Texas']
answer7

Bank Name     City  ST   CERT  \
4            Seaway Bank and Trust Company  Chicago  IL  19328   
21   The National Republic Bank of Chicago  Chicago  IL    916   
450         Millennium State Bank of Texas   Dallas  TX  57667   

    Acquiring Institution Closing Date Updated Date  
4     State Bank of Texas    27-Jan-17    18-May-17  
21    State Bank of Texas    24-Oct-14     6-Jan-16  
450   State Bank of Texas     2-Jul-09    26-Oct-12

In [ ]:
answer7[answer7['ST']=='TX']['ST'].count()

1

Bank Name     City  ST   CERT  \
4            Seaway Bank and Trust Company  Chicago  IL  19328   
21   The National Republic Bank of Chicago  Chicago  IL    916   
450         Millennium State Bank of Texas   Dallas  TX  57667   

    Acquiring Institution Closing Date Updated Date  
4     State Bank of Texas    27-Jan-17    18-May-17  
21    State Bank of Texas    24-Oct-14     6-Jan-16  
450   State Bank of Texas     2-Jul-09    26-Oct-12

### 8. What is the most common city in California for a bank to fail in?

In [ ]:
# CODE HERE
banks[banks['ST']=='CA']['City'].value_counts().head(1)


Los Angeles    4
Name: City, dtype: int64

Bank Name  ST  CERT  Acquiring Institution  Closing Date  \
City                                                                    
Los Angeles          4   4     4                      4             4   

             Updated Date  
City                       
Los Angeles             4

### 9. How many failed banks don't have the word "Bank" in their name? 

In [ ]:
# CODE HERE
banks[~banks['Bank Name'].str.contains('Bank')]['Bank Name'].count()

14

14

### 10. How many bank names start with the letter 's' ? 

In [ ]:
# CODE HERE

filter_s = [st for st in banks['Bank Name'] if st.startswith('S')]
len(filter_s)

53

53

### 11. How many CERT values are above 20000?

In [ ]:
# CODE HERE
banks[banks['CERT']>20000]['Bank Name'].count()

417

417

### 12. How many bank names consist of just two words? (e.g. "First Bank" , "Bank Georgia")

In [ ]:
# CODE HERE
# banks['Bank Word Count'] = banks['Bank Name'].apply(lambda x: len(str(x).split(' ')))
# banks[banks['Bank Word Count'] == 2]['Bank Name'].count()

sum(banks['Bank Name'].apply(lambda name: len(name.split()) == 2))

114

114

**Bonus: How many banks closed in the year 2008? (this is hard because we technically haven't learned about time series with pandas yet! Feel free to skip this one!**

In [ ]:
# CODE HERE
banks['Closing final Date'] = pd.to_datetime(banks['Closing Date'])
banks['Closing Year'] = banks['Closing final Date'].apply(lambda year: year.year)
banks[banks['Closing Year']==2008]['Bank Name'].count()

25

25

# Numpy Exercises

In [ ]:
import numpy as np

### 1. Create a null vector of size 10

In [ ]:
# CODE HERE
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 2. Create the 3x3 matrix with values in a range from 0 to 8

In [ ]:
# CODE HERE

#matrix = np.matrix('0 1 2 ;3 4 5;6 7 8')
#or
x =  np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 3. Create a random vector of size 30 and calculate the mean

In [ ]:
# CODE HERE
rand_vector = np.random.rand(2,30)
rand_vector.mean()

0.5379503246393107

#### 100 exercícios de NumPy

https://github.com/rougier/numpy-100

# GREAT JOB!